### ISSUE TITLE
Output to USART1-USART3 on Arduino AVR8 platform

### ISSUE THREAD

**Issue by starling13** [terminal-basic-team/terminalbasic#2]
Setting options
```
#define HAL_TERMINAL_NUM 2
#define HAL_TERMINAL_STDIO 1
```
in HAL_config.h, but output is still directed to USART0

**Comment by starling13** [comment]
Posibly fixed by b8f3d43

**Comment by grjonjon** [comment]
I guess that isn't an Arduino specific fix. The ucbasic_main.cpp isn't in the includes. So I can't apply the fix.

**Comment by starling13** [comment]
Arduino sketch is authored from the source in this repository. During this operation ucbasic_main.cpp becomes ucbasic_main.ino

**Comment by grjonjon** [comment]
Still, in the Arduino sketch 2.3-rc1 I can't see a "ucbasic..." file.

**Comment by starling13** [comment]
Sorry for mistake. It is renamed to terminal-basic.ino
